### ISSUE TITLE
How to add internal links inside the markdown?

### ISSUE THREAD

**Issue by ronald2wing** [swiftmade/blogdown#24]
It is an excellent tool for Laravel bloggers.
How do I refer to other posts and get their internal links within the markdown?

**Comment by aozisik** [comment]
Hi @ronald2wing 

Thank you!

The package currently makes no assumptions about under which route your blog posts are published. There's a default route, but it's also configurable. So we don't really have a way of determining the exact post URL just by its filename or slug.

The default router shows them at `blog/{slug}`, so you could very simply do this:

```php
<a href="/blog/{{ $slug }}">   
```

And in markdown, you could do the same...

```php
[link](/blog/{{ $slug }})
```
