### ISSUE TITLE
How do I add middleware to the blogs page?

### ISSUE THREAD

**Issue by ronald2wing** [swiftmade/blogdown#26]
I am trying to add middleware (this is in Laravel Folio syntax):
```
middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
]);
```
to the blogs page. The page does not get the account data without this middleware.

**Comment by aozisik** [comment]
Hi @ronald2wing 

Blogdown predates Laravel Folio, so I'm not sure if this package supports Laravel Folio router at all.

If you'd like to use custom routes / middleware, you might want to disable [Blogdown's default routes first.](https://github.com/swiftmade/blogdown/blob/5aeb97765fd7d8ab497e8c60fd686cb39d18c38a/src/config/blogdown.php#L14C6-L14C21)

**Comment by ronald2wing** [comment]
Very useful and customizable
