### ISSUE TITLE
Support Laravel 11

### ISSUE THREAD

**Issue by ronald2wing** [swiftmade/blogdown#27]
It looks like this package does not support Laravel 11 at the moment.

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires swiftmade/blogdown ^5.1 -> satisfiable by swiftmade/blogdown[v5.1.0].
    - swiftmade/blogdown v5.1.0 requires laravel/framework ^8.0|^9.0|^10.0 -> found laravel/framework[v8.0.0, .
.., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.3] but it conflicts with your root composer.json requ
ire (^11.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently l
ocked to specific versions.

**Comment by aozisik** [comment]
hi @ronald2wing 

Just introduced Laravel 11 support via v6.0.0.

**Comment by ronald2wing** [comment]
Thank you for your great package.
